language: node_js
node_js:
  - '8'

env:
  - NODE_ENV=testing

cache:
  directories:
    - "node_modules"
    - "client/node_modules"

addons:
  postgresql: "9.4"

services:
  - postgresql

install:
  - npm install -g codecov
  - npm install

before_script:
  - psql -c 'create database datapower_test;' -U postgres

script:
  - npm run lint
  - npm run build.client
  - npm run cover
  - npm run cover.report.ci
  - codecov
  - npm run test:client

notifications:
  email:
    on_success: never
    on_failure: always
