language: node_js
node_js:
  - '10'

env:
  global:
    - NODE_ENV=testing

cache:
  directories:
    - "node_modules"

addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-postgis-2.3

services:
  - postgresql

install:
  - npm install -g codecov
  - npm install -g lerna
  - lerna bootstrap

jobs:
  include:
    - stage: Build
      script:
        - lerna run lint
        - lerna run build
    - stage: Test
      before_script:
        - psql -U postgres -c 'create database twine_api_test'
        - psql -U postgres -c 'create extension postgis'
      script:
        - lerna run build
        - lerna run checks
        - lerna run cover

notifications:
  email:
    on_success: never
    on_failure: always
