language: node_js
node_js:
  - '8'

env:
  - NODE_ENV=test

cache:
  directories:
    - "node_modules"
    - "react-backend/client/node_modules"

addons:
  postgresql: "9.4"

services:
  - postgresql

install:
  - npm install -g codecov
  - npm install

before_script:
  - psql -c 'create database datapower_test;' -U postgres

script:
  - npm run lint
  - cd react-backend/client && npm run build
  - nyc npm test
  - nyc report --reporter=text-lcov > coverage.lcov
  - codecov

notifications:
  email:
    on_success: never
    on_failure: always
