language: node_js
node_js:
  - 'node'

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - psql -c 'create database datapower_test;' -U postgres

notifications:
  email:
    on_success: never
    on_failure: always