language: node_js
node_js:
  - 'node'

addons:
  postgresql: "9.4"

services:
  - postgresql

install:
  - npm install -g codecov

before_script:
  - psql -c 'create database datapower_test;' -U postgres

script:
  - npm run lint
  - nyc npm test
  - nyc report --reporter=text-lcov > coverage.lcov
  - codecov

notifications:
  email:
    on_success: never
    on_failure: always
